# Generated by Django 4.0.4 on 2022-04-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProject', models.CharField(max_length=50)),
                ('projectProgress', models.CharField(choices=[('Modelisation', 'Modelisation'), ('Design', 'Design'), ('Conception', 'Conception'), ('Deployement', 'Deployement'), ('Fin', 'Fin')], max_length=50, verbose_name='stat')),
                ('link_site', models.CharField(max_length=255)),
            ],
        ),
    ]
